version: 2
updates:
  - directory: /
    open-pull-requests-limit: 3
    package-ecosystem: nuget
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
    ignore:
      # Temporarily ignore these until we update the SDK
      - dependency-name: "System.Diagnostics.DiagnosticSource"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "BenchMarkDotNet"
        versions:
          - ">0.15.0"
