/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;
using OpenSearch.Net.Utf8Json;

namespace OpenSearch.Client
{
    [DataContract]
    public class DeleteAgenticMemoryQueryResponse : ResponseBase
    {
        [DataMember(Name = "batches")]
        public long? Batches { get; internal set; }

        [DataMember(Name = "created")]
        public long? Created { get; internal set; }

        [DataMember(Name = "deleted")]
        public long? Deleted { get; internal set; }

        [DataMember(Name = "failures")]
        public IList<object> Failures { get; internal set; }

        [DataMember(Name = "noops")]
        public long? Noops { get; internal set; }

        [DataMember(Name = "requests_per_second")]
        public float? RequestsPerSecond { get; internal set; }

        [DataMember(Name = "result")]
        public string Result { get; internal set; }

        [DataMember(Name = "retries")]
        public Retries Retries { get; internal set; }

        [DataMember(Name = "throttled_millis")]
        public long? ThrottledMillis { get; internal set; }

        [DataMember(Name = "throttled_until_millis")]
        public long? ThrottledUntilMillis { get; internal set; }

        [DataMember(Name = "timed_out")]
        public bool? TimedOut { get; internal set; }

        [DataMember(Name = "took")]
        public long? Took { get; internal set; }

        [DataMember(Name = "total")]
        public long? Total { get; internal set; }

        [DataMember(Name = "updated")]
        public long? Updated { get; internal set; }

        [DataMember(Name = "version_conflicts")]
        public long? VersionConflicts { get; internal set; }
    }
}
