/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;
using OpenSearch.Net.Utf8Json;

namespace OpenSearch.Client
{
    [JsonFormatter(typeof(OpenObjectFormatter<MLMetadata, IMLMetadata>))]
    [ReadAs(typeof(MLMetadata))]
    public interface IMLMetadata : IHasAdditionalProperties { }

    public class MLMetadata : IMLMetadata
    {
        public IDictionary<string, object> AdditionalProperties { get; set; }
    }

    public class MLMetadataDescriptor
        : DescriptorBase<MLMetadataDescriptor, IMLMetadata>,
            IMLMetadata
    {
        IDictionary<string, object> IHasAdditionalProperties.AdditionalProperties { get; set; }

        public MLMetadataDescriptor AdditionalProperties(
            IDictionary<string, object> additionalProperties
        ) =>
            Assign(
                additionalProperties,
                (a, v) => ((IHasAdditionalProperties)a).AdditionalProperties = v
            );
    }
}
