/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;
using OpenSearch.Net.Utf8Json;

namespace OpenSearch.Client
{
    [InterfaceDataContract]
    [ReadAs(typeof(MlNode))]
    public interface IMlNode
    {
        [DataMember(Name = "models")]
        IDictionary<string, IModelProfile> Models { get; set; }

        [DataMember(Name = "tasks")]
        IDictionary<string, IMlTask> Tasks { get; set; }
    }

    public class MlNode : IMlNode
    {
        public IDictionary<string, IModelProfile> Models { get; set; }
        public IDictionary<string, IMlTask> Tasks { get; set; }
    }

    public class MlNodeDescriptor : DescriptorBase<MlNodeDescriptor, IMlNode>, IMlNode
    {
        IDictionary<string, IModelProfile> IMlNode.Models { get; set; }
        IDictionary<string, IMlTask> IMlNode.Tasks { get; set; }

        public MlNodeDescriptor Models(IDictionary<string, IModelProfile> models) =>
            Assign(models, (a, v) => a.Models = v);

        public MlNodeDescriptor Tasks(IDictionary<string, IMlTask> tasks) =>
            Assign(tasks, (a, v) => a.Tasks = v);
    }
}
