/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;
using OpenSearch.Net.Utf8Json;

namespace OpenSearch.Client
{
    [StringEnum]
    public enum ModelState
    {
        [EnumMember(Value = "DEPLOY_FAILED")]
        DeployFailed,

        [EnumMember(Value = "DEPLOYED")]
        Deployed,

        [EnumMember(Value = "DEPLOYING")]
        Deploying,

        [EnumMember(Value = "PARTIALLY_DEPLOYED")]
        PartiallyDeployed,

        [EnumMember(Value = "REGISTERED")]
        Registered,

        [EnumMember(Value = "REGISTERING")]
        Registering,

        [EnumMember(Value = "UNDEPLOYED")]
        Undeployed,
    }
}
