/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;
using OpenSearch.Net.Utf8Json;

namespace OpenSearch.Client
{
    [InterfaceDataContract]
    [ReadAs(typeof(Strategy))]
    public interface IStrategy
    {
        [DataMember(Name = "configuration")]
        IStrategyConfiguration Configuration { get; set; }

        [DataMember(Name = "enabled")]
        bool? Enabled { get; set; }

        [DataMember(Name = "id")]
        string Id { get; set; }

        [DataMember(Name = "namespace")]
        IList<string> Namespace { get; set; }

        [DataMember(Name = "type")]
        StrategyType? Type { get; set; }
    }

    public class Strategy : IStrategy
    {
        public IStrategyConfiguration Configuration { get; set; }
        public bool? Enabled { get; set; }
        public string Id { get; set; }
        public IList<string> Namespace { get; set; }
        public StrategyType? Type { get; set; }
    }

    public class StrategyDescriptor : DescriptorBase<StrategyDescriptor, IStrategy>, IStrategy
    {
        IStrategyConfiguration IStrategy.Configuration { get; set; }
        bool? IStrategy.Enabled { get; set; }
        string IStrategy.Id { get; set; }
        IList<string> IStrategy.Namespace { get; set; }
        StrategyType? IStrategy.Type { get; set; }

        public StrategyDescriptor Configuration(IStrategyConfiguration configuration) =>
            Assign(configuration, (a, v) => a.Configuration = v);

        public StrategyDescriptor Enabled(bool? enabled = true) =>
            Assign(enabled, (a, v) => a.Enabled = v);

        public StrategyDescriptor Id(string id) => Assign(id, (a, v) => a.Id = v);

        public StrategyDescriptor Namespace(IList<string> @namespace) =>
            Assign(@namespace, (a, v) => a.Namespace = v);

        public StrategyDescriptor Type(StrategyType? type) => Assign(type, (a, v) => a.Type = v);
    }
}
