/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;
using OpenSearch.Net.Utf8Json;

namespace OpenSearch.Client
{
    [JsonFormatter(typeof(OpenObjectFormatter<ToolItems, IToolItems>))]
    [ReadAs(typeof(ToolItems))]
    public interface IToolItems : IHasAdditionalProperties
    {
        [DataMember(Name = "attributes")]
        IToolAttributes Attributes { get; set; }

        [DataMember(Name = "description")]
        string Description { get; set; }

        [DataMember(Name = "include_output_in_agent_response")]
        bool? IncludeOutputInAgentResponse { get; set; }

        [DataMember(Name = "name")]
        string Name { get; set; }

        [DataMember(Name = "parameters")]
        IParameters Parameters { get; set; }

        [DataMember(Name = "type")]
        string Type { get; set; }
    }

    public class ToolItems : IToolItems
    {
        public IToolAttributes Attributes { get; set; }
        public string Description { get; set; }
        public bool? IncludeOutputInAgentResponse { get; set; }
        public string Name { get; set; }
        public IParameters Parameters { get; set; }
        public string Type { get; set; }
        public IDictionary<string, object> AdditionalProperties { get; set; }
    }

    public class ToolItemsDescriptor : DescriptorBase<ToolItemsDescriptor, IToolItems>, IToolItems
    {
        IToolAttributes IToolItems.Attributes { get; set; }
        string IToolItems.Description { get; set; }
        bool? IToolItems.IncludeOutputInAgentResponse { get; set; }
        string IToolItems.Name { get; set; }
        IParameters IToolItems.Parameters { get; set; }
        string IToolItems.Type { get; set; }
        IDictionary<string, object> IHasAdditionalProperties.AdditionalProperties { get; set; }

        public ToolItemsDescriptor Attributes(IToolAttributes attributes) =>
            Assign(attributes, (a, v) => a.Attributes = v);

        public ToolItemsDescriptor Description(string description) =>
            Assign(description, (a, v) => a.Description = v);

        public ToolItemsDescriptor IncludeOutputInAgentResponse(
            bool? includeOutputInAgentResponse = true
        ) => Assign(includeOutputInAgentResponse, (a, v) => a.IncludeOutputInAgentResponse = v);

        public ToolItemsDescriptor Name(string name) => Assign(name, (a, v) => a.Name = v);

        public ToolItemsDescriptor Parameters(IParameters parameters) =>
            Assign(parameters, (a, v) => a.Parameters = v);

        public ToolItemsDescriptor Type(string type) => Assign(type, (a, v) => a.Type = v);

        public ToolItemsDescriptor AdditionalProperties(
            IDictionary<string, object> additionalProperties
        ) =>
            Assign(
                additionalProperties,
                (a, v) => ((IHasAdditionalProperties)a).AdditionalProperties = v
            );
    }
}
