/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;

namespace OpenSearch.Client
{
    public partial interface IUnloadModelRequest
    {
        [DataMember(Name = "model_ids")]
        IList<Id> ModelIds { get; set; }

        [DataMember(Name = "node_ids")]
        IList<Id> NodeIds { get; set; }
    }

    public partial class UnloadModelRequest
    {
        public IList<Id> ModelIds { get; set; }
        public IList<Id> NodeIds { get; set; }
    }

    public partial class UnloadModelDescriptor
    {
        IList<Id> IUnloadModelRequest.ModelIds { get; set; }
        IList<Id> IUnloadModelRequest.NodeIds { get; set; }

        public UnloadModelDescriptor ModelIds(IList<Id> modelIds) =>
            Assign(modelIds, (a, v) => a.ModelIds = v);

        public UnloadModelDescriptor NodeIds(IList<Id> nodeIds) =>
            Assign(nodeIds, (a, v) => a.NodeIds = v);
    }
}
