/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;

namespace OpenSearch.Client
{
    public partial interface IUpdateModelRequest
    {
        [DataMember(Name = "connector")]
        IDictionary<string, object> Connector { get; set; }

        [DataMember(Name = "connector_id")]
        string ConnectorId { get; set; }

        [DataMember(Name = "description")]
        string Description { get; set; }

        [DataMember(Name = "guardrails")]
        IGuardrails Guardrails { get; set; }

        [DataMember(Name = "interface")]
        IDictionary<string, object> Interface { get; set; }

        [DataMember(Name = "is_enabled")]
        bool? IsEnabled { get; set; }

        [DataMember(Name = "model_config")]
        IModelConfig ModelConfig { get; set; }

        [DataMember(Name = "name")]
        string Name { get; set; }

        [DataMember(Name = "rate_limiter")]
        IRateLimiter RateLimiter { get; set; }
    }

    public partial class UpdateModelRequest
    {
        public IDictionary<string, object> Connector { get; set; }
        public string ConnectorId { get; set; }
        public string Description { get; set; }
        public IGuardrails Guardrails { get; set; }
        public IDictionary<string, object> Interface { get; set; }
        public bool? IsEnabled { get; set; }
        public IModelConfig ModelConfig { get; set; }
        public string Name { get; set; }
        public IRateLimiter RateLimiter { get; set; }
    }

    public partial class UpdateModelDescriptor
    {
        IDictionary<string, object> IUpdateModelRequest.Connector { get; set; }
        string IUpdateModelRequest.ConnectorId { get; set; }
        string IUpdateModelRequest.Description { get; set; }
        IGuardrails IUpdateModelRequest.Guardrails { get; set; }
        IDictionary<string, object> IUpdateModelRequest.Interface { get; set; }
        bool? IUpdateModelRequest.IsEnabled { get; set; }
        IModelConfig IUpdateModelRequest.ModelConfig { get; set; }
        string IUpdateModelRequest.Name { get; set; }
        IRateLimiter IUpdateModelRequest.RateLimiter { get; set; }

        public UpdateModelDescriptor Connector(IDictionary<string, object> connector) =>
            Assign(connector, (a, v) => a.Connector = v);

        public UpdateModelDescriptor ConnectorId(string connectorId) =>
            Assign(connectorId, (a, v) => a.ConnectorId = v);

        public UpdateModelDescriptor Description(string description) =>
            Assign(description, (a, v) => a.Description = v);

        public UpdateModelDescriptor Guardrails(IGuardrails guardrails) =>
            Assign(guardrails, (a, v) => a.Guardrails = v);

        public UpdateModelDescriptor Interface(IDictionary<string, object> @interface) =>
            Assign(@interface, (a, v) => a.Interface = v);

        public UpdateModelDescriptor IsEnabled(bool? isEnabled = true) =>
            Assign(isEnabled, (a, v) => a.IsEnabled = v);

        public UpdateModelDescriptor ModelConfig(IModelConfig modelConfig) =>
            Assign(modelConfig, (a, v) => a.ModelConfig = v);

        public UpdateModelDescriptor Name(string name) => Assign(name, (a, v) => a.Name = v);

        public UpdateModelDescriptor RateLimiter(IRateLimiter rateLimiter) =>
            Assign(rateLimiter, (a, v) => a.RateLimiter = v);
    }
}
