/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using OpenSearch.Net;

namespace OpenSearch.Client
{
    /// <remarks>Supported by OpenSearch servers of version 2.12 or greater.</remarks>
    public partial interface IUpdateMemoryRequest
    {
        [DataMember(Name = "name")]
        string Name { get; set; }
    }

    public partial class UpdateMemoryRequest
    {
        public string Name { get; set; }
    }

    public partial class UpdateMemoryDescriptor
    {
        string IUpdateMemoryRequest.Name { get; set; }

        public UpdateMemoryDescriptor Name(string name) => Assign(name, (a, v) => a.Name = v);
    }
}
