on:
  workflow_dispatch: 
    inputs:
      branch:
        description: 'Branch to bump version on'
        required: true
      version:
        description: 'Version to bump to'
        required: true

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App Token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780
          
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ steps.github_app_token.outputs.token }}
      
      - name: Bump Version
        run: bash .github/bump-version.sh "${{ github.event.inputs.version }}"
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          base: ${{ github.event.inputs.branch }}
          branch: "feat/${{ github.event.inputs.branch }}/bump-version"
          commit-message: Bump version to ${{ github.event.inputs.version }}
          signoff: true
          delete-branch: true
          title: 'Bump version on ${{ github.event.inputs.branch }} to ${{ github.event.inputs.version }}.'
          labels: skip-changelog
          body: |
            Bumping version on `${{ github.event.inputs.branch }}` to `${{ github.event.inputs.version }}`.

