name: Code Generation

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # 00:00 UTC Weekly on Mondays

jobs:
  up_to_date:
    name: Ensure Generated Code Up To Date
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .NET Client
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 10.0.x

      - name: Cache Nuget Packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Run Code Generator
        run: ./build.sh codegen --branch main --include-high-level

      - name: Check For Uncommitted Changes
        shell: bash -eo pipefail {0}
        run: |
          output=$(git status --porcelain)
          if [ -z "$output" ]; then
            echo "Clean working directory"
            exit 0
          else
            echo "Dirty working directory"
            echo "$output"
            exit 1
          fi


  update_spec:
    name: Update Specification and Re-generate Code
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.repository == 'opensearch-project/opensearch-net')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout .NET Client
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 10.0.x

      - name: Cache Nuget Packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Download Latest Spec && Run Code Generator
        run: ./build.sh codegen --branch main --include-high-level --download

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Generate GitHub App Token
        id: github_app_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          commit-message: Re-generate client code using latest OpenSearch API specification (${{ steps.date.outputs.date }})
          title: Re-generated client code using latest OpenSearch API specification
          body: |
            Re-generated client code using latest OpenSearch API specification.
            Date: ${{ steps.date.outputs.date }}
          branch: code-gen/${{ github.ref_name }}/update
          signoff: true
          labels: |
            autocut
