name: YAML Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request: {}

jobs:
  test-yaml:
    name: YAML Tests (Released OpenSearch)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2.16.0
          - 2.14.0
          - 2.12.0
          - 2.10.0
          - 2.8.0
          - 2.6.0
          - 2.4.1
          - 1.3.14
    steps:
      - name: Checkout Client
        uses: actions/checkout@v4
        with:
          path: client

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Run OpenSearch
        id: opensearch
        uses: ./client/.github/actions/run-released-opensearch
        with:
          version: ${{ matrix.version }}
          secured: true
          opensearch_args: ${{ matrix.version == '2.8.0' && '-Eopensearch.experimental.feature.search_pipeline.enabled=true' || '' }}

      - name: Run YAML tests
        working-directory: client
        run: |
          dotnet run \
            --project ./tests/Tests.YamlRunner/Tests.YamlRunner.fsproj \
            -- \
            --endpoint $OPENSEARCH_URL \
            --auth-cert ./.ci/certs/kirk.p12 \
            --auth-cert-pass kirk \
            --junit-output-file ./test-results.xml
        env:
          OPENSEARCH_URL: ${{ steps.opensearch.outputs.opensearch_url }}

      - name: Save OpenSearch logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: opensearch-logs-${{ matrix.version }}
          path: |
            opensearch-*/logs/*

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: report-yaml-${{ matrix.version }}
          path: client/test-results.xml

  test-yaml-unreleased:
    name: YAML Tests (Unreleased OpenSearch)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { opensearch_ref: '1.x', java_version: '11' }
          - { opensearch_ref: '2.x', java_version: '21' }
          - { opensearch_ref: 'main', java_version: '21' }
    steps:
      - name: Checkout Client
        uses: actions/checkout@v4
        with:
          path: client

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}

      - name: Set JAVA${{ matrix.java_version }}_HOME
        run: echo "JAVA${{ matrix.java_version }}_HOME=$JAVA_HOME_${{ matrix.java_version }}_${{ runner.arch }}" >> $GITHUB_ENV

      - name: Checkout OpenSearch
        uses: actions/checkout@v4
        with:
          repository: opensearch-project/OpenSearch
          ref: ${{ matrix.opensearch_ref }}
          path: opensearch

      - name: Get OpenSearch commit SHA
        id: get-sha
        working-directory: opensearch
        run: echo "sha=$(git log -1 --format='%H')" >> $GITHUB_OUTPUT

      - name: Restore cached OpenSearch build
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: opensearch/distribution/archives/linux-tar/build/distributions
          key: opensearch-min-${{ steps.get-sha.outputs.sha }}

      - name: Assemble OpenSearch
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: opensearch
        run: ./gradlew :distribution:archives:linux-tar:assemble -Druntime.java=${{ matrix.java_version }}

      - name: Save cached OpenSearch build
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: opensearch/distribution/archives/linux-tar/build/distributions
          key: opensearch-min-${{ steps.get-sha.outputs.sha }}

      - name: Start OpenSearch
        run: |
          cd opensearch/distribution/archives/linux-tar/build/distributions
          tar xf opensearch-min-*
          OPENSEARCH_HOME=$(find . -maxdepth 1 -type d -name 'opensearch-min-*' | head -1 | xargs realpath)
          cp $GITHUB_WORKSPACE/client/.ci/opensearch/opensearch.yml $OPENSEARCH_HOME/config/opensearch.yml
          $OPENSEARCH_HOME/bin/opensearch &
          for attempt in {1..20}; do
            sleep 5
            if curl -s localhost:9200; then
              echo '=====> ready'
              break
            fi
            echo '=====> waiting...'
          done

      - name: Run YAML tests
        working-directory: client
        run: |
          dotnet run \
            --project ./tests/Tests.YamlRunner/Tests.YamlRunner.fsproj \
            -- \
            --endpoint http://localhost:9200 \
            --junit-output-file ./test-results.xml

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: report-yaml-unreleased-${{ matrix.opensearch_ref }}
          path: client/test-results.xml
