name: YAML Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request: {}

jobs:
  test-yaml:
    name: YAML Tests (Released OpenSearch)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2.11.1
          - 2.10.0
          - 2.8.0
          - 2.6.0
          - 2.4.1
          - 2.2.1
          - 2.0.1
          - 1.3.14
          - 1.2.4
          - 1.1.0
    steps:
      - name: Checkout Client
        uses: actions/checkout@v4
        with:
          path: client

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            8.0.x

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Run OpenSearch
        id: opensearch
        uses: ./client/.github/actions/run-released-opensearch
        with:
          version: ${{ matrix.version }}
          secured: true

      - name: Run YAML tests
        working-directory: client
        run: |
          dotnet run \
            --project ./tests/Tests.YamlRunner/Tests.YamlRunner.fsproj \
            -- \
            --endpoint $OPENSEARCH_URL \
            --auth-cert ./.ci/certs/kirk.p12 \
            --auth-cert-pass kirk \
            --junit-output-file ./test-results.xml
        env:
          OPENSEARCH_URL: ${{ steps.opensearch.outputs.opensearch_url }}

      - name: Save OpenSearch logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: opensearch-logs-${{ matrix.version }}
          path: |
            opensearch-*/logs/*

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: report-yaml-${{ matrix.version }}
          path: client/test-results.xml

  test-yaml-unreleased:
    name: YAML Tests (Unreleased OpenSearch)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opensearch_ref: ['1.x', '2.x', 'main']
    steps:
      - name: Checkout Client
        uses: actions/checkout@v4
        with:
          path: client

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            8.0.x

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Restore or Build OpenSearch
        id: opensearch_build
        uses: ./client/.github/actions/build-opensearch
        with:
          ref: ${{ matrix.opensearch_ref }}
          security_plugin: true

      - name: Unpack OpenSearch
        run: |
          tar -xzf ${{ steps.opensearch_build.outputs.distribution }} \
          && ./opensearch-*/bin/opensearch-plugin install --batch file://$(realpath ./opensearch-security/build/distributions/opensearch-security-*-SNAPSHOT.zip)

      - name: Start OpenSearch
        id: opensearch
        uses: ./client/.github/actions/start-opensearch
        with:
          secured: true

      - name: Run YAML tests
        working-directory: client
        run: |
          dotnet run \
            --project ./tests/Tests.YamlRunner/Tests.YamlRunner.fsproj \
            -- \
            --endpoint $OPENSEARCH_URL \
            --auth-cert ./.ci/certs/kirk.p12 \
            --auth-cert-pass kirk \
            --junit-output-file ./test-results.xml
        env:
          OPENSEARCH_URL: ${{ steps.opensearch.outputs.opensearch_url }}
          ADMIN_PASS: ${{ steps.opensearch.outputs.admin_password }}

      - name: Save OpenSearch logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: opensearch-logs-${{ matrix.opensearch_ref }}
          path: |
            opensearch-*/logs/*

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: report-yaml-unreleased-${{ matrix.opensearch_ref }}
          path: client/test-results.xml
