name: Draft a release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_approvers
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_approvers.outputs.approvers }}
          minimum-approvals: 2
          issue-title: 'Release opensearch-net'
          issue-body: "Please approve or deny the release of opensearch-net \n **TAG**: ${{ github.ref_name }}  \n **COMMIT**: ${{ github.sha }}"
          exclude-workflow-initiator-as-approver: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
