name: Create Release Candidate

on: [pull_request, push]
jobs:
  create-release-artifacts:
    name: Create Release Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Determine Version
      run: echo "VERSION=$(jq -r '.version' global.json)" | tee -a "$GITHUB_ENV"
    - name: Generate Release
      run: |
        ./build.sh release $VERSION
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/upload-artifact@v2
      with:
        name: opensearch-net-${{env.VERSION}}-release-candidate
        path: build/output/*.nupkg
