name: Draft a release

on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    name: Draft a release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      
      - id: get_data
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
          echo "version=$(jq -r '.version' global.json)" >> $GITHUB_OUTPUT

      - uses: trstringer/manual-approval@74d99dff7380e3e4b122d4ededcbca2b6ce59367 # v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ steps.get_data.outputs.approvers }}
          minimum-approvals: 1
          issue-title: 'Release opensearch-net : ${{ steps.get_data.outputs.version }}'
          issue-body: "Please approve or deny the release of opensearch-net. **VERSION**: ${{ steps.get_data.outputs.version }} **TAG**: ${{ github.ref_name }}  **COMMIT**: ${{ github.sha }}"
          exclude-workflow-initiator-as-approver: true

      - name: Draft a release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          immutableCreate: true
          generateReleaseNotes: true
          prerelease: true
