name: Create Release Candidate

on: [pull_request, push]
jobs:
  create-release-artifacts:
    name: Create Release Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: 10.0.x
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Determine Version
      run: echo "VERSION=$(jq -r '.version' global.json)" | tee -a "$GITHUB_ENV"
    - name: Generate Release
      run: |
        ./build.sh release $VERSION
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: opensearch-net-${{env.VERSION}}-release-candidate
        path: build/output/*.nupkg
