name: Create Release Candidate

on: [pull_request, push]
env:
    VERSION: 1.3.0
jobs:
  create-release-artifacts:
    name: Create Release Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.?sproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Generate Release
      run: |
        ./build.sh release $VERSION
    - uses: actions/upload-artifact@v2
      with:
        name: opensearch-net-${{env.VERSION}}-release-candidate
        path: build/output/*.nupkg
